# -*- coding: utf-8 -*-
"""Lab2_42

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z0Zu0i7M-05OvJqYBljTqB7-Ux6xjU3n
"""

import numpy as np
import matplotlib.pyplot as plt

x_train = np.array([1 ,2, 3, 4, 5, 6, 7])
y_train = np.array([300, 500, 800, 1000, 1300, 1500, 1800])
print(x_train)
print(y_train)

m = x_train.shape[0]
print(m)

i = 0
x_i = x_train[i]
y_i = y_train[i]
print(x_i)
print(y_i)

plt.scatter(x_train, y_train, marker='x', c='r')
plt.title("Housing Prices")
plt.ylabel('Price (in 1000s of dollars)')
plt.xlabel('Size (1000 sqft)')
plt.show

w = 240
b = 80
print(w)
print(b)

def compute_model_output(x , w ,b):
    m = x.shape[0]
    f_wb = np.zeros(m)
    for i in range(m):
      f_wb[i] = w * x[i] + b
    return f_wb

tmp_f_wb = compute_model_output(x_train, w , b)
plt.plot(x_train, tmp_f_wb, c='b')
plt.scatter(x_train, y_train, marker='x', c='r')
plt.show()

j_wb = 1 / 2 * m  * np.sum((tmp_f_wb - y_train) ** 2)
print(j_wb)