# -*- coding: utf-8 -*-
"""Lab3_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZAF-RxLmhfv5_dNojojrKaIP9JhfCECM
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.metrics import confusion_matrix
import seaborn as sn
from matplotlib import pyplot as plt

data = pd.read_csv('Iris.csv')
data

data['Species'] = data['Species'].replace({'Iris-setosa':1, 'Iris-versicolor':2, 'Iris-virginica':3})
data

X_train, X_test, y_train, y_test = train_test_split(data[['SepalLengthCm','SepalWidthCm','PetalLengthCm','PetalWidthCm']],data['Species'], test_size=0.3)

mymodel = linear_model.LogisticRegression(max_iter=120)
mymodel.fit(X_train, y_train)

mymodel.score(X_test, y_test)

predicted_output = mymodel.predict(X_test)
predicted_output

cm = confusion_matrix(y_test, predicted_output)
cm

plt.figure(figsize = (5,4))
sn.heatmap(cm, annot=True)
plt.xlabel('Predicted')
plt.ylabel('Truth or Actual Value')